name: Validate labels

on:
  pull_request_target:
    types: [labeled, unlabeled, opened, reopened, synchronize]

jobs:
  validate-labels:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') &&
      !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v4

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Verify Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx auto pr-check
          --url=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
